services:
  - type: web
    name: tracescope-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: VT_API_KEY
        sync: false

  - type: web
    name: tracescope-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
